# Generated by Django 3.1.3 on 2022-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221129_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default='content', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default='content', max_length=200),
        ),
    ]
